<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeLib>Shared</NativeLib>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ModelArtifacts/ModelArtifacts.csproj" />
  </ItemGroup>
</Project>
